name: Test and Deploy Mini Spotify

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Versão do Node.js
          cache: 'npm'        # Cache das dependências

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Configurar Cosmos DB (com credenciais do GitHub Secrets)
      - name: Test Cosmos DB Connection
        run: |
          node -e "
          const { CosmosClient } = require('@azure/cosmos');
          const endpoint = process.env.COSMOSDB_ENDPOINT;
          const key = process.env.CHAVE_AZURE;
          const client = new CosmosClient({ endpoint, key });

          async function testConnection() {
            try {
              const { database } = await client.databases.readAll().fetchAll();
              console.log('Conexão bem-sucedida ao Cosmos DB!');
              console.log(database);
            } catch (err) {
              console.error('Erro ao conectar ao Cosmos DB:', err.message);
            }
          }
          
          testConnection();
          "

      # Passo 5: Outras etapas do seu workflow (como deploy)
