name: Test and Deploy Mini Spotify

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Versão do Node.js
          cache: 'npm'        # Cache das dependências

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Testar conexão com o Cosmos DB
      - name: Test Cosmos DB Connection
        env:
          COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
          CHAVE_AZURE: ${{ secrets.CHAVE_AZURE }}
        run: |
          node -e "
          const { CosmosClient } = require('@azure/cosmos');

          // Verifique se as variáveis de ambiente estão definidas
          if (!process.env.COSMOSDB_ENDPOINT || !process.env.CHAVE_AZURE) {
            throw new Error('As variáveis de ambiente COSMOSDB_ENDPOINT e CHAVE_AZURE devem estar definidas.');
          }

          // Cria uma instância do cliente Cosmos DB
          const client = new CosmosClient({
            endpoint: process.env.COSMOSDB_ENDPOINT,
            key: process.env.CHAVE_AZURE
          });

          async function testConnection() {
            try {
              // Tenta acessar os bancos de dados
              const { resources: databases } = await client.databases.readAll().fetchAll();
              console.log('Conexão bem-sucedida ao Cosmos DB!');
              console.log(databases);
            } catch (err) {
              console.error('Erro ao conectar ao Cosmos DB:', err.message);
            }
          }
          
          testConnection();
          "
